# ABOUT THIS FILE
# ---------------
# Parameters in MARBL are divided into four different stages, based on the order in which they are set
# 1. General Parameters: variables that have no dependencies on other stages
# 2. PFT Counts: variables that can not be set until after PFT_defaults (in General Parameters) is known
# 3. PFT Derived Types: variables that can not be set until PFT Counts are known
#                       (autotroph_cnt, zooplankton_cnt, and max_grazer_prey_cnt)
# 4. Post-Tracer: variables that can not be set until the tracer count is known
#                 (tracer count depends on PFT Derived Types)
#
# All variables need to provide the following metadata:
# 1. longname: a description of the variable
# 2. category: when writing parameters to the log, MARBL will group variables by category
# 3. units: physical units (use "unitless" for pure numbers and "non-numeric" for strings / logicals)
# 4. datatype: integer, real, logical, or string
# 5. default_value: Value to use unless overwritten by the MARBL input file
#       NOTE: some parameters provide different default values for different configurations;
#             e.g. in CESM, the value of some parameters is resolution-dependent. In these
#             cases, default_value should be a dictionary with a "default" key and then keys
#             for whatever resolutions differ from the default.
#
#             Accepted keys:
#                1. default
#                2. CESM_x3
#
# There are also some optional metadata options:
# 1. valid_values: only values that MARBL will accept (default_value must be in valid_values!)
# 2. cannot change:
# 3. must set:
# 4. append_to_config_keywords:
#
# TODO: parameters that are arrays?

_order : ["general_parms", "PFT_counts", "PFT_derived_types"]

# Category 1: General Parameters
general_parms :
   PFT_defaults :
      longname : Define how PFTs are initialized
      category : config PFTs
      units : unitless
      datatype : string
      default_value : CESM2
      valid_values : CESM2, user-specified
      append_to_config_keywords : true
   ciso_on :
      longname : Control whether CISO tracer module is active
      category : config flags
      units : unitless
      datatype : logical
      default_value : false
   lsource_sink :
      longname : Control which portions of code are executed (useful for debugging)
      category : config flags
      units : unitless
      datatype : logical
      default_value : true
   ciso_lsource_sink :
      longname : Control which portions of the carbon isotope code are executed (useful for debugging)
      category : config flags
      units : unitless
      datatype : logical
      default_value : true
   lecovars_full_depth_tavg :
      longname : Control whether base ecosystem variables are written full depth
      category : config flags
      units : unitless
      datatype : logical
      default_value : false
   ciso_lecovars_full_depth_tavg :
      longname : Control whether carbon isotope variables are written full depth
      category : config flags
      units : unitless
      datatype : logical
      default_value : false
   lflux_gas_o2 :
      longname : Control which portions of code are executed (useful for debugging)
      category : config flags
      units : unitless
      datatype : logical
      default_value : true
   lflux_gas_co2 :
      longname : Control which portions of code are executed (useful for debugging)
      category : config flags
      units : unitless
      datatype : logical
      default_value : true
   lcompute_nhx_surface_emis :
      longname : Control if NHx emissions are computed
      category : config flags
      units : unitless
      datatype : logical
      default_value : true
   lvariable_PtoC :
      longname : Control if PtoC ratios in autotrophs vary
      category : config flags
      units : unitless
      datatype : logical
      default_value : true
   ladjust_bury_coeff :
      longname : Control if bury coefficients are adjusted (rather than constant)
      category : config flags
      units : unitless
      datatype : logical
      default_value : false
   init_bury_coeff_opt :
      longname : Source of initial burial coefficient
      category : config strings
      units : unitless
      datatype : string
      default_value : nml
   parm_Fe_bioavail :
      longname : Fraction of Fe flux that is bioavailable
      category : general parmeters
      units : unitless
      datatype : real
      default_value : 1.0
   parm_o2_min :
      longname : Minimum O2 needed for production & consumption
      category : general parmeters
      units : nmol/cm^3
      datatype : real
      default_value : 5.0
   parm_o2_min_delta :
      longname : Width of min O2 range
      category : general parmeters
      units : nmol/cm^3
      datatype : real
      default_value : 5.0
   parm_kappa_nitrif_per_day :
      longname : Nitrification inverse time constant
      category : general parmeters
      units : 1/day
      datatype : real
      default_value : 0.06
   parm_nitrif_par_lim :
      longname : PAR limit for nitrification
      category : general parameters
      units : W/m^2
      datatype : real
      default_value : 1.0
   parm_labile_ratio :
      longname : Fraction of loss to DOC that routed directly to DIC
      category : general parmeters
      units : unitless
      datatype : real
      default_value : 0.94
   parm_init_POC_bury_coeff :
      longname : Initial scale factor for burial of POC, PON
      category : general parameter
      units : unitless
      datatype : real
      default_value : # default value is resolution dependent!
         default : 1.1
         grid = CESM_x3 : 5.0
   parm_init_POP_bury_coeff :
      longname : Initial scale factor for burial of POP
      category : general parameter
      units : unitless
      datatype : real
      default_value : # default value is resolution dependent!
         default : 1.1
         grid = CESM_x3 : 5.0
   parm_init_bSi_bury_coeff :
      longname : Initial scale factor for burial of bSi
      category : general parameter
      units : unitless
      datatype : real
      default_value : # default value is resolution dependent!
         default : 1.0
         grid = CESM_x3 : 1.1
   parm_Fe_scavenge_rate0 :
      longname : Scavenging base rate for Fe
      category : general parameter
      units : unitless
      datatype : real
      default_value : 15
   parm_Lig_scavenge_rate0 :
      longname : Scavenging base rate for bound ligand
      category : general parameter
      units : unitless
      datatype : real
      default_value : 0.015
   parm_FeLig_scavenge_rate0 :
      longname : Scavenging base rate for bound iron
      category : general parameter
      units : unitless
      datatype : real
      default_value : 1.3
   parm_Lig_degrade_rate0 :
      longname : Fe-binding ligand bacterial degradation base rate coefficient
      category : general parameter
      units : unitless
      datatype : real
      default_value : 0.000094
   parm_Fe_desorption_rate0 :
      longname : Desorption rate for scavenged Fe from particles
      category : general parameter
      units : unitless
      datatype : real
      default_value : 1e-6
   parm_f_prod_sp_CaCO3 :
      longname : Fraction of sp production as CaCO3 production
      category : general parameter
      units : unitless
      datatype : real
      default_value : # default value is resolution dependent!
         default : 0.07
         grid = CESM_x3 : 0.075
   parm_POC_diss :
      longname : Base POC dissipation length scale
      category : general parameter
      units : cm
      datatype : real
      default_value : 100e2
   parm_SiO2_diss :
      longname : Base SiO2 dissipation length scale
      category : general parameter
      units : cm
      datatype : real
      default_value : 770e2
   parm_CaCO3_diss :
      longname : Base CaCO3 dissipation length scale
      category : general parameter
      units : cm
      datatype : real
      default_value : 500e2
   parm_sed_denitrif_coeff :
      longname : Global scaling factor for sed_denitrif
      category : general parameter
      units : unitless
      datatype : real
      default_value : 1
   bury_coeff_rmean_timescale_years :
      longname : Running mean time scale for bury coefficients
      category : general parameter
      units : years
      datatype : real
      default_value : 10
   parm_scalelen_z :
      longname : Depths of prescribed scalelen values
      category : Scale lengths
      units : cm
      datatype : real(4)
      default_value : 100.0e2, 250.0e2, 500.0e2, 1000.0e2
   parm_scalelen_vals :
      longname : Prescribed scalelen values
      category : Scale lengths
      units : unitless
      datatype : real(4)
      default_value : 1, 2.2, 4, 5

# Category 2: PFT_counts
PFT_counts :
   autotroph_cnt :
      longname : Number of autotroph classes
      category : config PFTs
      units : unitless
      datatype : integer
      default_value : 3
      cannot change : PFT_defaults == 'CESM2'
      must set : PFT_defaults == 'user-specified'
   zooplankton_cnt :
      longname : Number of zooplankton classes
      category : config PFTs
      units : unitless
      datatype : integer
      default_value : 1
   max_grazer_prey_cnt :
      longname : Number of grazer prey classes
      category : config PFTs
      units : unitless
      datatype : integer
      default_value : 3

# Category 3: PFTs
PFT_derived_types :
   autotrophs :
      category : autotrophs
      datatype :
         # Components of the derived type
         # (_type_name is not part of the type)
         _type_name : autotrophs_type(:)
         sname :
            longname : Short name of the autotroph
            units : non-numeric
            datatype : string
            default_value :
               default : UNSET
               autotroph = sp : sp
               autotroph = diat : diat
               autotroph = diaz : diaz
         lname :
            longname : Long name of the autotroph
            units : non-numeric
            datatype : string
            default_value :
               default : UNSET
               autotroph = sp : Small Phyto
               autotroph = diat : Diatom
               autotroph = diaz : Diazotroph
         Nfixer :
            longname : Flag set to true if autotroph fixes nitrogen
            units : non-numeric
            datatype : logical
            default_value :
               default : false
               autotroph = diaz : true
         imp_calcifier :
            longname : Flag set to true if autotroph implicitly handles calcification
            units : non-numeric
            datatype : logical
            default_value :
               default : false
               autotroph = sp : true