# ABOUT THIS FILE
# ---------------
# Parameters in MARBL are divided into four different stages, based on the order in which they are set
# 1. General Parameters: variables that have no dependencies on other stages
# 2. PFT Counts: variables that can not be set until after PFT_defaults (in General Parameters) is known
# 3. PFT Derived Types: variables that can not be set until PFT Counts are known
#                       (autotroph_cnt, zooplankton_cnt, and max_grazer_prey_cnt)
# 4. Post-Tracer: variables that can not be set until the tracer count is known
#                 (tracer count depends on PFT Derived Types)
#
# All variables need to provide the following metadata:
# 1. longname: a description of the variable
# 2. category: when writing parameters to the log, MARBL will group variables by category
# 3. units: physical units (use "unitless" for pure numbers and "non-numeric" for strings / logicals)
# 4. datatype: integer, real, logical, or string
# 5. default_value: Value to use unless overwritten by the MARBL input file
#
# There are also some optional metadata options:
# 1. valid_values: only values that MARBL will accept (default_value must be in valid_values!)
#
# TODO: parameters that are arrays?

# Category 1: General Parameters
general_parms :
  PFT_defaults :
    longname : Define how PFTs are initialized
    category : config PFTs
    units : unitless
    datatype : string
    default_value : CESM2
    valid_values : CESM2, user-specified
  ciso_on :
    longname : Control whether CISO tracer module is active
    category : config flags
    units : unitless
    datatype : logical
    default_value : false
  lsource_sink :
    longname : Control which portions of code are executed (useful for debugging)
    category : config flags
    units : unitless
    datatype : logical
    default_value : true
  ciso_lsource_sink :
    longname : Control which portions of the carbon isotope code are executed (useful for debugging)
    category : config flags
    units : unitless
    datatype : logical
    default_value : true
  lecovars_full_depth_tavg :
    longname : Control whether base ecosystem variables are written full depth
    category : config flags
    units : unitless
    datatype : logical
    default_value : false
  ciso_lecovars_full_depth_tavg :
    longname : Control whether carbon isotope variables are written full depth
    category : config flags
    units : unitless
    datatype : logical
    default_value : false
  lflux_gas_o2 :
    longname : Control which portions of code are executed (useful for debugging)
    category : config flags
    units : unitless
    datatype : logical
    default_value : true
  lflux_gas_co2 :
    longname : Control which portions of code are executed (useful for debugging)
    category : config flags
    units : unitless
    datatype : logical
    default_value : true
  lcompute_nhx_surface_emis :
    longname : Control if NHx emissions are computed
    category : config flags
    units : unitless
    datatype : logical
    default_value : true
  lvariable_PtoC :
    longname : Control if PtoC ratios in autotrophs vary
    category : config flags
    units : unitless
    datatype : logical
    default_value : true
  ladjust_bury_coeff :
    longname : Control if bury coefficients are adjusted (rather than constant)
    category : config flags
    units : unitless
    datatype : logical
    default_value : false
  init_bury_coeff_opt :
    longname : Source of initial burial coefficient
    category : config flags
    units : unitless
    datatype : string
    default_value : nml
  parm_Fe_bioavail :
    longname : Fraction of Fe flux that is bioavailable
    category : config flags
    units : unitless
    datatype : real
    default_value : 1.0_r8
  parm_o2_min :
    longname : Minimum O2 needed for production & consumption
    category : config flags
    units : nmol/cm^3
    datatype : real
    default_value : 5.0_r8
  parm_o2_min_delta :
    longname : Width of min O2 range
    category : config flags
    units : nmol/cm^3
    datatype : real
    default_value : 5.0_r8

# Category 2: PFT_counts
PFT_counts :
  autotroph_cnt :
    longname : Number of autotroph classes
    category : config PFTs
    units : unitless
    datatype : integer
    default_value : 3
  zooplankton_cnt :
    longname : Number of zooplankton classes
    category : config PFTs
    units : unitless
    datatype : integer
    default_value : 1
  max_grazer_prey_cnt :
    longname : Number of grazer prey classes
    category : config PFTs
    units : unitless
    datatype : integer
    default_value : 3