# ABOUT THIS FILE
# ---------------
# Parameters in MARBL are divided into four different stages, based on the order in which they are set
# 1. General Parameters: variables that have no dependencies on other stages
# 2. PFT Counts: variables that can not be set until after PFT_defaults (in General Parameters) is known
# 3. PFT Derived Types: variables that can not be set until PFT Counts are known
#                       (autotroph_cnt, zooplankton_cnt, and max_grazer_prey_cnt)
# 4. Post-Tracer: variables that can not be set until the tracer count is known
#                 (tracer count depends on PFT Derived Types)
#
# All variables need to provide the following metadata:
# 1. longname: a description of the variable
# 2. category: when writing parameters to the log, MARBL will group variables by category
# 3. units: physical units (use "unitless" for pure numbers and "non-numeric" for strings / logicals)
# 4. datatype: integer, real, logical, or string
# 5. default_value: Value to use unless overwritten by the MARBL input file
#
# There are also some optional metadata options:
# 1. valid_values: only values that MARBL will accept (default_value must be in valid_values!)
#
# TODO: parameters that are arrays?

# Category 1: General Parameters
general_parms :
  PFT_defaults :
    longname : Define how PFTs are initialized
    category : config PFTs
    units : unitless
    datatype : string
    default_value : CESM2
    valid_values : CESM2, user-specified
  ciso_on :
    longname : Control whether CISO tracer module is active
    category : config flags
    units : unitless
    datatype : logical
    default_value : false
  lsource_sink :
    longname : Control which portions of code are executed (useful for debugging)
    category : config flags
    units : unitless
    datatype : logical
    default_value : true
  ciso_lsource_sink :
    longname : Control which portions of the carbon isotope code are executed (useful for debugging)
    category : config flags
    units : unitless
    datatype : logical
    default_value : true

# Category 2: PFT_counts
PFT_counts :
  autotroph_cnt :
    longname : Number of autotroph classes
    category : config PFTs
    units : unitless
    datatype : integer
    default_value : 3
  zooplankton_cnt :
    longname : Number of zooplankton classes
    category : config PFTs
    units : unitless
    datatype : integer
    default_value : 1
  max_grazer_prey_cnt :
    longname : Number of grazer prey classes
    category : config PFTs
    units : unitless
    datatype : integer
    default_value : 3